repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        files: '^infrastructure/.*'
        exclude: infrastructure/.secrets.baseline
        args: ['--baseline', 'infrastructure/.secrets.baseline']
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
    -   id: terraform_fmt
    -   id: terraform_validate
    -   id: terraform_docs
        args:
            - markdown table --recursive --output-file README.md .
    # -   id: terraform_tfsec
-   repo: https://github.com/bridgecrewio/checkov.git
    rev: 2.3.261
    hooks:
    -   id: checkov
        args: [--quiet, --compact]
