containers:
  utility:
    build_directory: .
    dockerfile: Dockerfile
    working_directory: /src
    volumes:
      - local: .
        container: /src

tasks:
  security-scan:
    description: Scan the terraform stack for security vulnerabilities
    run:
      container: utility
      command: bash -c 'checkov -d ./blocks --quiet'

  generate_latest_changelog:
    description: Parse the changelog file for the release's changes
    run:
      container: utility
      command: 'python get_latest_release_changelog.py'
