name: Check application status
on:
  workflow_dispatch:
jobs:
  check-status:
    runs-on: self-hosted
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Run E2E tests
      env:
        DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
        DATA_BUCKET: ${{ secrets.DATA_BUCKET }}
        AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
        RESOURCE_PREFIX: ${{ secrets.RESOURCE_PREFIX }}
        ALLOWED_EMAIL_DOMAINS: ${{ secrets.ALLOWED_EMAIL_DOMAINS }}
      run: pytest test/e2e -v

    - name: Run UI Tests
      env:
        DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
      run: make test-ui
