name: rAPId Release

on:
  release:
    types: [released]

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log commit SHA
        run: echo $GITHUB_SHA

  api-release:
    needs:
      - setup
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Populate .env with additional vars
        run: |
          cp ./.github/.github.env .env
          echo AWS_ACCOUNT=${{ secrets.AWS_ACCOUNT }} >> .env
          echo AWS_REGION=${{ secrets.AWS_REGION }} >> .env

      - name: Build API Image
        run: make api-create-image

      - name: API Tag and Upload Release Image
        run: make api-tag-and-upload-release-image

  sdk-release:
    needs:
      - setup
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Populate .env with additional vars
        run: |
          echo "TWINE_USERNAME=${{ secrets.TWINE_USERNAME_TEST }}" >> .env
          echo "TWINE_PASSWORD=${{ secrets.TWINE_PASSWORD_TEST }}" >> .env
          echo TWINE_NON_INTERACTIVE=${{ secrets.TWINE_NON_INTERACTIVE }} >> .env

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Setup Python Environment
        run: |
          make sdk-setup
          source sdk/.venv/bin/activate

      - name: SDK Release
        run: make sdk-release

  ui-release:
    needs:
      - setup
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install UI Packages
        run: make ui-setup

      - name: UI Build Static Files
        run: make ui-create-static-out

      - name: UI Zip and Release
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: make ui-zip-and-release tag=$TAG

  cleanup:
    needs:
      - setup
      - api-release
      - sdk-release
      - ui-release
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clean Docker Context
        if: always()
        run: make clean-pipeline-docker-context
